os:
  - osx
  - linux

language: generic

sudo: required
dist: trusty

osx_image: xcode8.3

script:
  - eval "$(curl -sL https://swift.skrundz.ca/ci)"
  - eval "$(curl -sL https://swift.skrundz.ca/codecov)"
